word_list=[]
word_dict={}

for word in open("word_list.txt","r"):
	word_list.append(word.rstrip("\n").lower())

'''
#create word dict
alphas="abcdefghijklmnopqrstuvwxyz"
for alpha in alphas:
	word_dict[alpha]=[]
	for word in word_list:
		if word.startswith(alpha):
			word_dict[alpha].append(word)'''

#write word_list & word_dict
with open("word_list.py","w") as file1:
	code="""
	
#DO NOT EDIT THIS FILE
#created by 'create_list.py'
	
word_list= {}

	""".format(word_list)
	file1.write(code)


	
